version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: Gadget-Store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  your_app:
    build: .
    ports:
      - "9096:9095"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Gadget-Store
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL-AUTO: create
      SPRING_JPA_SHOW-SQL: "true"
      SPRING_JWT_SECRET_KEY: java10
